### ISSUE TITLE
Depending on `ndx_icephys_meta` extension is outdated?

### ISSUE THREAD

**Issue by weiglszonja** [catalystneuro/ndx-hierarchical-behavioral-data#10]
This came up during our meeting with @bendichter that `HierarchicalBehavioralTable` class builds upon `HierarchicalDynamicTableMixin` which is from `ndx_icephys_meta` and that this might be outdated. 
Can we just build `HierarchicalBehavioralTable` from `TimeIntervals` and `DynamicTable`? We did not manage to find reference for a HierarchicalDynamicTable in `hdmf`. 

@rly @oruebel

**Comment by bendichter** [comment]
Yes, it looks like we should just be inheriting from `TimeIntervals` and use stand-alone functions like https://github.com/hdmf-dev/hdmf/blob/dev/src/hdmf/common/hierarchicaltable.py#L17 instead of class methods

**Comment by oruebel** [comment]
> Yes, it looks like we should just be inheriting from `TimeIntervals` and use stand-alone functions

Yes, that is correct, just use a DynamicTable with DynamicTableRegion columns. The main reason this functionality got moved to helper functions when we merged ndx_icephys with NWB, is: 1) the schema for a hierarchical and a regular dynamic table are the same (the only difference is that a hierarchical table contains a column of type DynamicTableRegion), i.e., the HiearchicalDynamicTable class only added helper functions but did not define a new type   2) adding all the helper functions directly to DynamicTable would have made the DynamicTable class (which is already very complex) even larger, 3) we wanted to keep this functionality separate. 

Just FYI, the functions to convert hierarchical tables to a flat table currently only follow the first DynamicTableRegion column, see the comment here:

https://github.com/hdmf-dev/hdmf/blob/e7d1c8e3e8ad9c27820c93d0c15bc351cc4eb498/src/hdmf/common/hierarchicaltable.py#L21-L24

I.e., if you are using multiple DynamicTableRegion columns in a table, then the column you want to resolve should be listed first. Or we would need to enhance https://github.com/hdmf-dev/hdmf/blob/dev/src/hdmf/common/hierarchicaltable.py to make sure it can deal with this case properly (which would be useful to do in general but wasn't necessary for the icephys tables)

**Comment by bendichter** [comment]
@oruebel thanks for the clarification. I don't anticipate the single DTR constraint will be an issue for us. @weiglszonja do you think you can make this change?

**Comment by weiglszonja** [comment]
Thanks @oruebel for the detailed help! I'll take a look at it tomorrow and let you know how it goes. 👍

**Comment by oruebel** [comment]
> I don't anticipate the single DTR constraint will be an issue for

That's great. BTW, just to avoid possible confusion, from a schema perspective there are no constraints on how many DynamicTableRegion columns one can define for a DynamicTable; this is purely a current limitations of the helper functions in https://github.com/hdmf-dev/hdmf/blob/dev/src/hdmf/common/hierarchicaltable.py
