### ISSUE TITLE
publish on ndx catalog

### ISSUE THREAD

**Issue by bendichter** [catalystneuro/ndx-hierarchical-behavioral-data#9]
instructions: https://github.com/nwb-extensions/ndx-template/blob/main/%7B%7B%20cookiecutter.namespace%20%7D%7D/NEXTSTEPS.md

**Comment by weiglszonja** [comment]
@luiztauffer I'm happy to do this based on your example for [ndx-sound](https://github.com/nwb-extensions/staged-extensions/pull/29) if you're ok with it!

**Comment by luiztauffer** [comment]
@weiglszonja sure, sounds good!

**Comment by weiglszonja** [comment]
@luiztauffer 
it was merged already in https://github.com/nwb-extensions/staged-extensions/pull/30, but then why is it we don't see it in https://nwb-extensions.github.io ?

**Comment by weiglszonja** [comment]
Closing as it is in https://nwb-extensions.github.io
